---

  - name: Include global variables.
    include_vars: "vars.yml"

  # Include variables and define needed variables.
  - name: Include OS-specific variables.
    include_vars: "{{ ansible_os_family }}.yml"

  - name: Include Ubuntu 14 variables.
    include_vars: "vars.Ubuntu14.yml"
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

  - name: Ensure openssh-client is available (including ssh-keygen tool)
    when: ansible_os_family == 'Debian'
    apt:
        update_cache: yes
        cache_valid_time: 600
        name: 'openssh-client'
        state: present

  - name: Ensure openssh-client is available (including ssh-keygen tool)
    when: ansible_os_family == 'RedHapt'
    yum:
        name: 'openssh'
        state: present

  - name: Create Aegir Group (so we can set the GID)
    group:
      name: "{{ aegir_user_name }}"
      state: present
      gid: "{{ aegir_user_uid }}"

  - name: Create Aegir user
    when: aegir_create_user == 'yes'
    user:
      name: "{{ aegir_user_name }}"
      shell: /bin/bash
      group: "{{ aegir_user_name }}"
      system: yes
      home: "{{ aegir_user_home }}"
      generate_ssh_key: yes
      uid: "{{ aegir_user_uid }}"

  - name: Ensure /var/aegir is owned by aegir user.
    file:
      state: directory
      path: "{{ aegir_user_home }}"
      group: "{{ aegir_user_name }}"
      owner: "{{ aegir_user_name }}"

  # Aegir's CentOS installation requires this.
  - name: Set appropriate permissions for Aegir's home folder.
    command: chmod -R 755 {{ aegir_user_home }}
    when: ansible_os_family == "RedHat"

  - name: Create aegir's config folder
    file:
      path: "{{ aegir_user_home }}/config"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      state: directory
      mode: 0755

  - name: Create aegir's logs folder
    file:
      path: "{{ aegir_logs_path }}"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      state: directory
      mode: 0755

  - name: Create aegir's authorized keys file
    copy:
      dest: "{{ aegir_user_home }}/.ssh/authorized_keys"
      owner: "{{ aegir_user_name }}"
      group: "{{ aegir_user_name }}"
      content: "{{ aegir_user_authorized_keys }}"
      mode: 0644
